[package]
name = "cooklang-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-html = "0.2"
cooklang = "0.15"
serde-wasm-bindgen = "0.6"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
