[package]
name = "cooklang-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-html = "0.2.1"
cooklang = "0.13.3"
serde_json = "1.0.132"
wasm-bindgen = "0.2.95"

[lib]
crate-type = ["cdylib", "rlib"]
